server:
  port: 38092

spring:
  datasource:
    url: jdbc:mysql://192.168.115.6:50027/MMT-dev?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    database: 3
    url: redis://:123456@192.168.115.6:6379
lark-robot:
  url: https://open.feishu.cn/open-apis/bot/v2/hook/
  dev: true
minio:
  endpoint: http://192.168.115.10:9000 #Minio服务所在地址
  bucketName: mmt #存储桶名称
  accessKey: minio #访问的key
  secretKey: miniopass #访问的秘钥
  publicAddress: http://localhost/mmt # 不含多余/的协议+域名